DELETE FROM ENDERECO;
DELETE FROM CONSULTA;
DELETE FROM FUNCIONARIO;
DELETE FROM TIPO_FUNCIONARIO;
DELETE FROM VACINA_ANIMAL;
DELETE FROM VACINA;
DELETE FROM ALERGIA_ANIMAL;
DELETE FROM ALERGIA;
DELETE FROM ANIMAL;
DELETE FROM ESPECIE;
DELETE FROM TIPO_ANIMAL;
DELETE FROM DONO;

INSERT INTO DONO (CPF, NOME, NASCIMENTO) VALUES (99999999999, 'José da Silva', to_date('01/02/03', 'DD/MM/YYYY'));
INSERT INTO DONO (CPF, NOME, NASCIMENTO) VALUES (123456789, 'Maria da Silva', to_date('19/02/1980', 'DD/MM/YYYY'));
INSERT INTO DONO (CPF, NOME, NASCIMENTO) VALUES (111, 'Pedro', to_date('01/02/1982', 'DD/MM/YYYY'));

INSERT INTO TIPO_ANIMAL (ACRONIMO, NOME) VALUES ('CAO', 'Cachorro');
INSERT INTO TIPO_ANIMAL (ACRONIMO, NOME) VALUES ('GAT', 'Gato');

INSERT INTO ESPECIE (NOME, DESCRICAO, TIPO_ANIMAL_ACRONIMO) VALUES ('Cachorro Comum', 'Um tipo de cachorro vira-latas', 'CAO');
INSERT INTO ESPECIE (NOME, DESCRICAO, TIPO_ANIMAL_ACRONIMO) VALUES ('Gato Comum', 'Um tipo de gato', 'GAT');

INSERT INTO ANIMAL (ESPECIE_ID, DONO_ID, NOME, NASCIMENTO)
SELECT ESPECIE.ID, DONO.ID, 'Totó', to_date('01/01/2013', 'DD/MM/YYYY') FROM ESPECIE, DONO
WHERE ESPECIE.NOME = 'Cachorro Comum' and CPF = 99999999999;

INSERT INTO ANIMAL (ESPECIE_ID, DONO_ID, NOME, NASCIMENTO)
SELECT ESPECIE.ID, DONO.ID, 'Cãochorro', to_date('01/01/2012', 'DD/MM/YYYY') FROM ESPECIE, DONO
WHERE ESPECIE.NOME = 'Gato Comum' and CPF = 99999999999;

INSERT INTO ANIMAL (ESPECIE_ID, DONO_ID, NOME, NASCIMENTO)
SELECT ESPECIE.ID, DONO.ID, 'Tom', to_date('01/01/2015', 'DD/MM/YYYY') FROM ESPECIE, DONO
WHERE ESPECIE.NOME = 'Gato Comum' and CPF = 123456789;

INSERT INTO ANIMAL (ESPECIE_ID, DONO_ID, NOME, NASCIMENTO)
SELECT ESPECIE.ID, DONO.ID, 'Gatuno', to_date('01/01/2011', 'DD/MM/YYYY') FROM ESPECIE, DONO
WHERE ESPECIE.NOME = 'Gato Comum' and CPF = 123456789;

INSERT INTO VACINA (NOME, DESCRICAO) VALUES ('anti-rábica', 'Vacina contra raiva');
INSERT INTO VACINA (NOME, DESCRICAO) VALUES ('hepatite', 'Vacina contra Hepatite');

INSERT INTO VACINA_ANIMAL (ANIMAL_ID, VACINA_ID, DATAVACINACAO, DESCRICAOVETERINARIO)
SELECT A.ID, V.ID, '2015-01-01', 'Vacina 1 de 3' FROM ANIMAL A, VACINA V
WHERE A.NOME = 'Totó' AND V.NOME = 'anti-rábica';

INSERT INTO VACINA_ANIMAL (ANIMAL_ID, VACINA_ID, DATAVACINACAO, DESCRICAOVETERINARIO)
SELECT A.ID, V.ID, '2015-02-01', 'Vacina 2 de 3' FROM ANIMAL A, VACINA V
WHERE A.NOME = 'Totó' AND V.NOME = 'anti-rábica';

INSERT INTO VACINA_ANIMAL (ANIMAL_ID, VACINA_ID, DATAVACINACAO, DESCRICAOVETERINARIO)
SELECT A.ID, V.ID, '2015-03-01', 'Vacina 3 de 3' FROM ANIMAL A, VACINA V
WHERE A.NOME = 'Totó' AND V.NOME = 'anti-rábica';

INSERT INTO ALERGIA (NOMEALERGIA, DESCRICAO) VALUES ('Rinite', 'Alergia ao pó');
INSERT INTO ALERGIA (NOMEALERGIA, DESCRICAO) VALUES ('Polen', 'Alergia a flores');

INSERT INTO ALERGIA_ANIMAL (ANIMAL_ID, ALERGIA_ID)
SELECT A.ID, AL.ID FROM ANIMAL A, ALERGIA AL
WHERE A.NOME = 'Tom' AND AL.NOMEALERGIA = 'Rinite';

INSERT INTO ALERGIA_ANIMAL (ANIMAL_ID, ALERGIA_ID)
SELECT A.ID, AL.ID FROM ANIMAL A, ALERGIA AL
WHERE A.NOME = 'Tom' AND AL.NOMEALERGIA = 'Polen';

INSERT INTO ALERGIA_ANIMAL (ANIMAL_ID, ALERGIA_ID)
SELECT A.ID, AL.ID FROM ANIMAL A, ALERGIA AL
WHERE A.NOME = 'Totó' AND AL.NOMEALERGIA = 'Rinite';

INSERT INTO ALERGIA_ANIMAL (ANIMAL_ID, ALERGIA_ID)
SELECT A.ID, AL.ID FROM ANIMAL A, ALERGIA AL
WHERE A.NOME = 'Totó' AND AL.NOMEALERGIA = 'Polen';

INSERT INTO TIPO_FUNCIONARIO (CODIGOTIPO, DESCRICAO)
VALUES ('SEC', 'Funcionário responsável pela secretaria');

INSERT INTO TIPO_FUNCIONARIO (CODIGOTIPO, DESCRICAO)
VALUES ('VET', 'Veterinário');

INSERT INTO FUNCIONARIO (NOME,CPF,NASCIMENTO,DATAADMISSAO,TIPO_FUNCIONARIO_CODIGOTIPO)
VALUES('Alonso',5555555,'2000-12-01','2016-12-01','SEC');

INSERT INTO FUNCIONARIO (NOME,CPF,NASCIMENTO,DATAADMISSAO,TIPO_FUNCIONARIO_CODIGOTIPO)
VALUES('Jonas',666666666,'1989-01-01','2010-12-01','VET');

INSERT INTO FUNCIONARIO (NOME,CPF,NASCIMENTO,DATAADMISSAO,TIPO_FUNCIONARIO_CODIGOTIPO)
VALUES('Cleide',77777777,'1999-10-01','2008-12-01','VET');

INSERT INTO CONSULTA (ANIMAL_ID,DATAHORA_CONSULTA,FUNCIONARIO_AGEND_ID,VETERINARIO_ID)
SELECT A.ID, '2017-01-01 15:30:00', FUNC.ID, VET.ID FROM ANIMAL A, FUNCIONARIO FUNC, FUNCIONARIO VET
WHERE A.NOME = 'Totó' AND FUNC.CPF = 5555555 AND VET.CPF = 666666666;

INSERT INTO CONSULTA (ANIMAL_ID,DATAHORA_CONSULTA,FUNCIONARIO_AGEND_ID,VETERINARIO_ID)
SELECT A.ID, '2017-02-03 14:00:00', FUNC.ID, VET.ID FROM ANIMAL A, FUNCIONARIO FUNC, FUNCIONARIO VET
WHERE A.NOME = 'Totó' AND FUNC.CPF = 5555555 AND VET.CPF = 666666666;

INSERT INTO CONSULTA (ANIMAL_ID,DATAHORA_CONSULTA,FUNCIONARIO_AGEND_ID,VETERINARIO_ID)
SELECT A.ID, '2017-02-04 15:30:00', FUNC.ID, VET.ID FROM ANIMAL A, FUNCIONARIO FUNC, FUNCIONARIO VET
WHERE A.NOME = 'Tom' AND FUNC.CPF = 5555555 AND VET.CPF = 666666666;

INSERT INTO CONSULTA (ANIMAL_ID,DATAHORA_CONSULTA,FUNCIONARIO_AGEND_ID,VETERINARIO_ID)
SELECT A.ID, '2017-02-05 14:00:00', FUNC.ID, VET.ID FROM ANIMAL A, FUNCIONARIO FUNC, FUNCIONARIO VET
WHERE A.NOME = 'Gatuno' AND FUNC.CPF = 5555555 AND VET.CPF = 666666666;

INSERT INTO CONSULTA (ANIMAL_ID,DATAHORA_CONSULTA,FUNCIONARIO_AGEND_ID,VETERINARIO_ID)
SELECT A.ID, '2017-03-05 15:00:00', FUNC.ID, VET.ID FROM ANIMAL A, FUNCIONARIO FUNC, FUNCIONARIO VET
WHERE A.NOME = 'Totó' AND FUNC.CPF = 5555555 AND VET.CPF = 666666666;

INSERT INTO CONSULTA (ANIMAL_ID,DATAHORA_CONSULTA,FUNCIONARIO_AGEND_ID,VETERINARIO_ID)
SELECT A.ID, '2017-03-10 16:00:00', FUNC.ID, VET.ID FROM ANIMAL A, FUNCIONARIO FUNC, FUNCIONARIO VET
WHERE A.NOME = 'Totó' AND FUNC.CPF = 5555555 AND VET.CPF = 666666666;

INSERT INTO CONSULTA (ANIMAL_ID,DATAHORA_CONSULTA,FUNCIONARIO_AGEND_ID,VETERINARIO_ID)
SELECT A.ID, '2017-03-10 17:00:00', FUNC.ID, VET.ID FROM ANIMAL A, FUNCIONARIO FUNC, FUNCIONARIO VET
WHERE A.NOME = 'Tom' AND FUNC.CPF = 5555555 AND VET.CPF = 666666666;

INSERT INTO CONSULTA (ANIMAL_ID,DATAHORA_CONSULTA,FUNCIONARIO_AGEND_ID,VETERINARIO_ID)
SELECT A.ID, '2017-03-12 18:00:00', FUNC.ID, VET.ID FROM ANIMAL A, FUNCIONARIO FUNC, FUNCIONARIO VET
WHERE A.NOME = 'Tom' AND FUNC.CPF = 5555555 AND VET.CPF = 666666666;

INSERT INTO CONSULTA (ANIMAL_ID,DATAHORA_CONSULTA,FUNCIONARIO_AGEND_ID,VETERINARIO_ID)
SELECT A.ID, '2017-03-15 19:00:00', FUNC.ID, VET.ID FROM ANIMAL A, FUNCIONARIO FUNC, FUNCIONARIO VET
WHERE A.NOME = 'Tom' AND FUNC.CPF = 5555555 AND VET.CPF = 666666666;

INSERT INTO CONSULTA (ANIMAL_ID,DATAHORA_CONSULTA,FUNCIONARIO_AGEND_ID,VETERINARIO_ID)
SELECT A.ID, '2017-03-20 20:00:00', FUNC.ID, VET.ID FROM ANIMAL A, FUNCIONARIO FUNC, FUNCIONARIO VET
WHERE A.NOME = 'Tom' AND FUNC.CPF = 5555555 AND VET.CPF = 666666666;

INSERT INTO ENDERECO (dono_id, logradouro, bairro, numero, cidade, cep)
select id,'rua do dono','meu bairro',23,'Curitiba',2345678 from dono d where d.cpf = 99999999999;

INSERT INTO ENDERECO (dono_id, logradouro, bairro, numero, cidade, cep)
select id,'rua do dono','meu bairro',23,'Curitiba',2345678 from dono d where d.cpf = 123456789;